### ISSUE TITLE
How I can Site URL Change?

### ISSUE THREAD

**Issue by emresaracoglu** [sourcegraph/sourcegraph-jetbrains#1]
Hello,

How can I change the search URL address? I can not see any panels of the plugin in PHPStorm.

or is this not possible?

Thanks

**Comment by sqs** [comment]
It’s admittedly not as easy as it should be, but it’s possible:

https://github.com/sourcegraph/sourcegraph-jetbrains/blob/master/README.md#settings

Improving this is on the TODO list.

**Comment by slimsag** [comment]
Closing in favor of #7 -- as noted this is currently possible using https://github.com/sourcegraph/sourcegraph-jetbrains/blob/master/README.md#settings
