### ISSUE TITLE
Private instance - Open and copy don't work but search does  

### ISSUE THREAD

**Issue by ranihorev** [sourcegraph/sourcegraph-jetbrains#24]
I created the `sourcegraph-jetbrains.properties` file and I can search for code snippets, but the open and copy commands don't do anything

**Comment by coury-clark** [comment]
@muratsu I just tried the open in diff view that I merged and it also isn't working - looks like there may be some regression with the URL work

**Comment by ranihorev** [comment]
My bad, I should've done a better job reading the docs:

> By default, the plugin will use the origin git remote to determine which repository on Sourcegraph corresponds to your local repository. If your origin remote doesn’t match Sourcegraph, you may instead configure a sourcegraph Git remote which will take priority.

Now it works :)
