### ISSUE TITLE
Feature Request: GUI Integration

### ISSUE THREAD

**Issue by KristofMorva** [sourcegraph/sourcegraph-jetbrains#34]
Hey there,

I was wondering if Sourcegraph could be integrated into the IDE GUI, similarly to global search (Ctrl+Shift+F)? Opening it in a separate browser window doesn't feel really good UX-wise.

![image](https://user-images.githubusercontent.com/5695015/155121968-703e1f2b-d9c8-4892-be0b-b5a424a8b54b.png)

**Comment by vdavid** [comment]
You're in luck, my fellow Hungarian developer! 😊
Some of us in the Sourcegraph team are also avid JetBrains users. We share your pain and we're already working on a better plugin. (Note that we already have a [Sourcegraph plugin](https://plugins.jetbrains.com/plugin/9682-sourcegraph), but it opens the search results in the browser.)
I can't give you a release date, but we're on it. 🧑🏽‍💻
Let me know if you're interested in participating in user tests or getting early access. (Not a promise, but if you say you're interested, we might reach out to you in the coming weeks.)

**Comment by coury-clark** [comment]
Hey @KristofMorva! I'm also a big Jetbrains user, and I worked on a hackathon project that might be along the lines of what you're thinking: https://www.loom.com/share/56a0be3f38ff424aa863946dfe5d72bd

@vdavid is one of the devs that is going to build this out in a real (non-hackathon 😄) way. It's something we are thinking about internally, for sure!

**Comment by KristofMorva** [comment]
> You're in luck, my fellow Hungarian developer! 😊 Some of us in the Sourcegraph team are also avid JetBrains users. We share your pain and we're already working on a better plugin. (Note that we already have a [Sourcegraph plugin](https://plugins.jetbrains.com/plugin/9682-sourcegraph), but it opens the search results in the browser.) I can't give you a release date, but we're on it. 🧑🏽‍💻 Let me know if you're interested in participating in user tests or getting early access. (Not a promise, but if you say you're interested, we might reach out to you in the coming weeks.)

Awesome news @vdavid, thank you, sure, sign me up! 😇
