### ISSUE TITLE
Sourcegraph: Open does not open to commit sha

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph-jetbrains#5]
When triggering the Sourcegraph: Open command, the commit sha should be included so that a permalink can be created and so that contents of the file are the same as what the user is seeing in their editor.

**Additional context:**
- If you're on a branch, the branch name will be included.
- If you're in detached head, no commit sha is passed so the open command will target the default branch.

**Comment by erezeshkol** [comment]
Just to add to this: I might be wrong, but it looks like this might require a change to the Sourcegraph frontend itself, as the [/editor endpoint](https://github.com/sourcegraph/sourcegraph/blob/f92a751f39df40decb710d8d6d606f2a6e4df788/cmd/frontend/internal/app/editor.go#L47) doesn't seem to support commit SHAs at the moment.

**Comment by KattMingMing** [comment]
@erezeshkol - Yep that's correct. I've filed an issue for this here: https://github.com/sourcegraph/sourcegraph/issues/952
