### ISSUE TITLE
Open does not open to custom url

### ISSUE THREAD

**Issue by ananthrn** [sourcegraph/sourcegraph-jetbrains#8]
I added a file sourcegraph-jetbrains.properties in the home directory of my repository and added a custom url using ```url =```. The open and search commands do not search in the specific url though.

**Comment by slimsag** [comment]
Hello, apologies for the massively delayed response. The `sourcegraph-jetbrains.properties` file is to be placed in your $HOME directory on your system, not in the repository itself. It is a global configuration file.

Please file a new issue if this doesn't suite your use case!
